package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/liamp/gox/ast"
)

type OutputFile struct {
	Filename string
	Content  string
}

type Generator struct {
	imports  map[string]bool
	buf      strings.Builder
	sumTypes map[string]*ast.SumType
}

func New() *Generator {
	return &Generator{
		imports:  make(map[string]bool),
		sumTypes: make(map[string]*ast.SumType),
	}
}

func (g *Generator) Generate(file *ast.File, sourceFile string) []OutputFile {
	g.buf.Reset()
	g.imports = make(map[string]bool)
	g.sumTypes = make(map[string]*ast.SumType)

	for _, decl := range file.Decls {
		if st, ok := decl.(*ast.SumType); ok {
			g.sumTypes[st.Name] = st
		}
	}

	for _, imp := range file.Imports {
		g.imports[imp.Path] = true
	}

	var body strings.Builder
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.SumType:
			body.WriteString(g.emitSumType(d))
		case *ast.Contract:
			body.WriteString(g.emitContract(d))
		case *ast.Func:
			body.WriteString(g.emitFunc(d))
		}
	}

	g.buf.WriteString(fmt.Sprintf("// Code generated by gox from %s. DO NOT EDIT.\n", sourceFile))
	g.buf.WriteString(fmt.Sprintf("package %s\n", file.Package))

	if len(g.imports) > 0 {
		sorted := make([]string, 0, len(g.imports))
		for imp := range g.imports {
			sorted = append(sorted, imp)
		}
		sort.Strings(sorted)
		g.buf.WriteString("\nimport (\n")
		for _, imp := range sorted {
			g.buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		g.buf.WriteString(")\n")
	}

	g.buf.WriteString(body.String())

	src, err := format.Source([]byte(g.buf.String()))
	if err != nil {
		return []OutputFile{{
			Filename: strings.TrimSuffix(sourceFile, ".gox") + "_gen.go",
			Content:  g.buf.String(),
		}}
	}

	return []OutputFile{{
		Filename: strings.TrimSuffix(sourceFile, ".gox") + "_gen.go",
		Content:  string(src),
	}}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
