// Code generated by gox from contract_basic.gox. DO NOT EDIT.
package users

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name,omitempty"`
}

type CreateUserOutput struct {
	Id        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
}

type CreateUserError interface {
	isCreateUserError()
}

type CreateUserErrorEmailTaken struct{}

func (CreateUserErrorEmailTaken) isCreateUserError() {}

type CreateUserErrorWeakPassword struct{}

func (CreateUserErrorWeakPassword) isCreateUserError() {}

func ValidateCreateUserInput(in CreateUserInput) error {
	var errs []string
	if in.Email == "" {
		errs = append(errs, "email: required")
	}
	if in.Email != "" && !strings.Contains(in.Email, "@") {
		errs = append(errs, "email: invalid email")
	}
	if in.Password == "" {
		errs = append(errs, "password: required")
	}
	if in.Password != "" && len(in.Password) < 8 {
		errs = append(errs, "password: min length 8")
	}
	if len(errs) > 0 {
		return fmt.Errorf("%s", strings.Join(errs, "; "))
	}
	return nil
}

func CreateUserHandler(fn func(CreateUserInput) (CreateUserOutput, CreateUserError)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		var in CreateUserInput
		if err := json.NewDecoder(r.Body).Decode(&in); err != nil {
			w.WriteHeader(400)
			json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
			return
		}
		if err := ValidateCreateUserInput(in); err != nil {
			w.WriteHeader(422)
			json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
			return
		}
		out, cerr := fn(in)
		if cerr != nil {
			switch cerr.(type) {
			case CreateUserErrorEmailTaken:
				w.WriteHeader(409)
				json.NewEncoder(w).Encode(map[string]string{"error": "email taken"})
			case CreateUserErrorWeakPassword:
				w.WriteHeader(400)
				json.NewEncoder(w).Encode(map[string]string{"error": "weak password"})
			}
			return
		}
		json.NewEncoder(w).Encode(out)
	}
}

func CreateUserClient(baseURL string, in CreateUserInput) (CreateUserOutput, CreateUserError, error) {
	body, err := json.Marshal(in)
	if err != nil {
		return CreateUserOutput{}, nil, fmt.Errorf("marshal: %w", err)
	}
	resp, err := http.Post(baseURL+"/api/users", "application/json", bytes.NewReader(body))
	if err != nil {
		return CreateUserOutput{}, nil, fmt.Errorf("request: %w", err)
	}
	defer resp.Body.Close()
	switch resp.StatusCode {
	case 200:
		var out CreateUserOutput
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			return CreateUserOutput{}, nil, fmt.Errorf("decode: %w", err)
		}
		return out, nil, nil
	case 409:
		return CreateUserOutput{}, CreateUserErrorEmailTaken{}, nil
	case 400:
		return CreateUserOutput{}, CreateUserErrorWeakPassword{}, nil
	default:
		return CreateUserOutput{}, nil, fmt.Errorf("unexpected status: %d", resp.StatusCode)
	}
}
