// Code generated by gox from sumtype_basic.gox. DO NOT EDIT.
package orders

import (
	"time"
)

type OrderState interface {
	isOrderState()
}

type OrderStatePending struct{}

func (OrderStatePending) isOrderState() {}

type OrderStatePaid struct {
	Amount float64
	PaidAt time.Time
}

func (OrderStatePaid) isOrderState() {}

type OrderStateShipped struct {
	TrackingNumber string
}

func (OrderStateShipped) isOrderState() {}

type OrderStateCancelled struct {
	Reason string
}

func (OrderStateCancelled) isOrderState() {}
